sudo: required

services:
  - docker

before_install:
  - docker build -t willtaylor093/react-test -f ./client/Dockerfile.dev 
  
script:
  - docker run -t willtaylor093/react-test npm test -- --coverage

after_success:
  - docker build -t willtaylor093/multi-client ./client
  - docker build -t willtaylor093/multi-nginx ./nginx
  - docker build -t willtaylor093/multi-server ./server
  - docker build -t willtaylor093/multi-worker ./worker
  # Login in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push the images to docker hub
  - docker push willtaylor093/multi-client
  - docker push willtaylor093/multi-nginx
  - docker push willtaylor093/multi-server
  - docker push willtaylor093/multi-worker

